### ISSUE TITLE
Game Activity not tracking new playtime entries

### ISSUE THREAD

**Issue by apachpoland** [Lacro59/playnite-gameactivity-plugin#105]
This is continuation of closed Issue #99. 
Game Activity is not logging session playtime. Extension doesnt record date end session time or it sets end date time equal to date start (see screenshot 1). After I noticed that, I updated my playtime manually and basically forced Game Activity to accept different end date. Result can be seen on screenshot 2. After this action I was able to see new entry on chart. So to fix issue when Game Activity doesnt records new entries for end date it must be check if extension is able to overwrite this entry as expected.
![s1](https://user-images.githubusercontent.com/98308598/151714670-0652679d-e272-42ea-927c-4ab80bbb86dd.png)
![s2](https://user-images.githubusercontent.com/98308598/151714672-819b85f0-0289-46d3-900f-d2b3095bc191.png)
.

**Comment by apachpoland** [comment]
What I also noticed Platform icon is not correct. When I was signalizing game activity file I noticed that source Id sometimes has this value 
2bf81e43-4ab8-44a3-920e-d58f6f2f797f
sometimes this
00000000-0000-0000-0000-000000000000.
I dont know if it is relevant.

**Comment by Terrance** [comment]
I also have my end times not being recorded (first started some time after 23rd December).

Related to the null platform IDs, I'm seeing lots of this in my extension log:

> 29-01 12:05:24.038|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000

**Comment by Lacro59** [comment]
Can you try with the last version?

**Comment by Terrance** [comment]
Updated to 2.7, tracking seems to be working for me.  👍

(Got a startup failure on the first restart after updating, though nothing untoward in the logs and I updated a handful of addons at once, so I'm going to assume it was one of the others...  second startup worked fine.)
