### ISSUE TITLE
GameActivity causes Playnite to crash on startup

### ISSUE THREAD

**Issue by Hernald** [Lacro59/playnite-gameactivity-plugin#114]
This is with the latest update. Disabling GameActivity solved the problem. But it would be nice to have GameActivity running again.

**Comment by Lacro59** [comment]
Can you post your crash report or playnite.log?

**Comment by Hernald** [comment]
[playnite.log](https://github.com/Lacro59/playnite-gameactivity-plugin/files/8016184/playnite.log)
Playnite seems to have opened okay this time but it failed a couple or three times since the last update. I'll update if I have any more trouble.

**Comment by Hernald** [comment]
[GameActivity_2022-02-08.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/8026030/GameActivity_2022-02-08.zip)
As promised. I don't know if this is part of the same problem. The game crashed and then its link to Playnite was broken. A message came up on Playnite saying that permission to write to a save file was denied.
