### ISSUE TITLE
Decrease performance hit by only processing when controls are in view

### ISSUE THREAD

**Issue by darklinkpower** [Lacro59/playnite-gameactivity-plugin#115]
I noticed that there was a noticeable slowdown on my system like this:

- Start Playnite. Active view is Grid View.
- Select a game. There's a slight slowdown/lag when selecting a game
- Switch to another view with plugin controls implemented, like Grid View to Details View
- Select a game. The slowdown hit is much more noticeable.
- Switch back to Grid View.
- Selecting a game has a much more noticeable slowdown when selecting a game than before.

This happens because the `GameContextChanged` method in the control always rised when selecting a game, even if it is done in a view different than the control. What I did to solve this is to not do any processing if the control is not in the active view https://github.com/darklinkpower/PlayniteExtensionsCollection/blob/master/source/Generic/ExtraMetadataLoader/Controls/LogoLoaderControl.xaml.cs#L65-L81

I've implemented this in all the controls on plugins I've made and it improves processing a lot, if you can I think it would be great if you could do this in this and your other plugins.

**Comment by darklinkpower** [comment]
Another thing that I did in some plugins is use a timer to not instantly update on each game selection by using a timer, this way the processing will only be done when the user has stopped moving the selection.

https://github.com/darklinkpower/PlayniteExtensionsCollection/blob/master/source/Generic/NewsViewer/PluginControls/NewsViewerControl.xaml.cs#L300-L302

https://github.com/darklinkpower/PlayniteExtensionsCollection/blob/master/source/Generic/NewsViewer/PluginControls/NewsViewerControl.xaml.cs#L331-L342

Although I don't know if this is a good approach and it's not something that can be used on all plugins. Perhaps it could be used for some plugins like GameActivity and SuccessStory that I think are doing more processing in their controls.

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-plugincommon/commit/b99d148485c84a21f0e96d6e6a45eba777986e74
