### ISSUE TITLE
Don't update games data file if nothing changed

### ISSUE THREAD

**Issue by darklinkpower** [Lacro59/playnite-gameactivity-plugin#117]
Currently it seems that the plugin updates data file even if the data is not different data than before, I think it could be better if it only did that when the new data is different since it causing a lot of writes that I think are unnecessary

![image](https://user-images.githubusercontent.com/1389286/154311989-6ad0510c-8c0c-465f-8c6b-206948b21221.png)

Original file:

![image](https://user-images.githubusercontent.com/1389286/154312140-caadb942-5485-43b4-89f8-86a17f18aa3a.png)

New file (Has same data):
![image](https://user-images.githubusercontent.com/1389286/154312250-2bfa9946-2084-4f46-94e1-ec91a81e6272.png)

**Comment by Lacro59** [comment]
I have done some tests and have not been able to reproduce this problem.
