### ISSUE TITLE
Error message - Failed to load listGameActivities

### ISSUE THREAD

**Issue by aarish-codev** [Lacro59/playnite-gameactivity-plugin#12]
Getting below error. 
I know its not your extension issue, but the issue is I messed up some installed game due to windows re-install or game deletion.
I am using Playnite portable version.
I know that removing and re-installing the plugin should solve this issue, but I just dont want that my last 1 month playtime data to be lost, all the charts, hour count that your extension provides.

Please let me know how can I remove these 1-2 game details from the extension manually so that this error goes.
Again thanks for the lovely extension.

![image](https://user-images.githubusercontent.com/25772331/89045816-c813f780-d369-11ea-852e-8474fcd9936b.png)

**Comment by aarish-codev** [comment]
Never mind, I gone through the code and found out the individual .json files. Removed it and error is gone.

**Comment by Lacro59** [comment]
It's possible to have a extract from Playnite.log in Playnite folder?
I will can see the problem and resolvr it for the nexte time.

**Comment by aarish-codev** [comment]
Hi, issue is when I remove the game from playnite library its json data is not removed from GameActivity plugin folder and due to this the error as shared in screenshot occurs.

It got fixed when I manually removed the uuid json files from game activity data folder.
