### ISSUE TITLE
GPU stats don't update until Playnite is restarted

### ISSUE THREAD

**Issue by EhGuppy** [Lacro59/playnite-gameactivity-plugin#135]
When I start Playnite and start a game, all stats are logged properly the first time. But, until Playnite is restarted, GameActivity will report the GPU stats from the first game played for each subsequent game.

![GameActivitybug3](https://user-images.githubusercontent.com/71322236/158951264-8b143e30-5fd0-4ede-9375-2105c305a099.png)

**Comment by Hernald** [comment]
This also happens with successive data for the same game. It appears that once GPU is measured it is not cleared for another reading until Playnite is closed down completely and reopened,

**Comment by Hernald** [comment]
If I removed the gpValue == 0 condition in the update at 381 - 387 of GameActivity.cs this might solve my problem but create others. So I will leave it alone and hope that someone more qualified gets to look at this sometime.
