### ISSUE TITLE
Crashing with duplicate key error

### ISSUE THREAD

**Issue by Twiggy547** [Lacro59/playnite-gameactivity-plugin#142]
having an issue with GA crashing anytime its opened Playnite crashes immediately if opened by the side/top bar buttons or if opened from the extensions submenu will load the window and not crash but display an error that says "Failed to execute menu action. An item with the same key has already been added." 
happens across multiple themes and with all other extensions disabled.
the error seems to be about using a dictionary and trying to create the same key multiple times

[logs.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/8692016/logs.zip)

**Comment by Lacro59** [comment]
Can you try this version?
[playnite-gameactivity-plugin_2_7_1.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/8707934/playnite-gameactivity-plugin_2_7_1.zip)

**Comment by Twiggy547** [comment]
Fixed the issue! 👍
