### ISSUE TITLE
Wrong Icons in Sources View

### ISSUE THREAD

**Issue by Ciriviel** [Lacro59/playnite-gameactivity-plugin#145]
The Sources for Nintendo 3DS and Nintendo DS use the Origin Launcher icon instead of their own.
![icon issue](https://user-images.githubusercontent.com/35538331/169271307-7d405ab8-f3c9-4803-8ff7-f0b79da97388.png)

This issue extends to everywhere the icon is used, e.g. Source View, below the "total hours" graph as well as the session overview.
GameActivity is set to use its own icons, not the ones defined via Playnite.

Thank you in advance!

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-plugincommon/commit/e282b3e2ba9ca98ee0d16ecc09ab7e47994c04f9
