### ISSUE TITLE
Backup data notification for all "non-steam" games

### ISSUE THREAD

**Issue by SgtSARS** [Lacro59/playnite-gameactivity-plugin#151]
I launch all of my non-steam games through steam using a "link" play action. After playing any of these games, when restarting Playnite I receive notifications of backup data for those games "likely due to a Playnite crash," even though there was no crash. If I accept these notifications it adds the time played on top of it having already been added, essentially doubling the length of a session. I have gotten into the habit of just opening each notification and clicking "remove" every time I open Playnite, but it would be nice if there was a way to stop receiving false crash alerts.

**Comment by Lacro59** [comment]
Can you give an example of a "link" you are using?

**Comment by Lacro59** [comment]
Can you post your extension;log & playnite.log?

**Comment by SgtSARS** [comment]
Hey Lacro, thanks for getting back to me but sometime since when I posted this I started organizing my library differently (no longer launching all non-Steam games through Steam) and the issue hasn't come up in several months. So i can't say if it's even still something that happens. If there haven't been any other complaints this issue can probably be closed.
