### ISSUE TITLE
Bug: Gantt view not working in Playnite 10 and GameActivity 3.0

### ISSUE THREAD

**Issue by hitsu4yrkl** [Lacro59/playnite-gameactivity-plugin#164]
At least for me, the gantt view is not working anymore since updating to Playnite 10 and GameActivity 3.0. Everything else is working perfectly, but when I click on gantt view there is just nothing, as seen here:

![image](https://user-images.githubusercontent.com/82475806/191933317-4d51fd03-999e-4625-8add-f6d9c5dceac6.png)

**Comment by Skylin3r** [comment]
same here

**Comment by Lacro59** [comment]
can you post your extension.log?
