### ISSUE TITLE
Transparent background in mouseover text

### ISSUE THREAD

**Issue by flzubuduuz** [Lacro59/playnite-gameactivity-plugin#168]
All mouseover text (the text that pops up when you hover your mouse over a graph bar) has a transparent background. I don't know whether this is intended or not, but it makes the text hard to discern in some circumstances. This issue also occurs when viewing an individual game's activity.

![image](https://user-images.githubusercontent.com/80221875/192820433-35125aef-8c7b-4f1c-aef4-06fda90c18c1.png)
![image](https://user-images.githubusercontent.com/80221875/192821495-6ddb4ab1-583e-42ef-8497-149f3d7d85cf.png)

**Comment by Lacro59** [comment]
fixed with #166
