### ISSUE TITLE
Can't see detailed data graph bars from Game Activity tab

### ISSUE THREAD

**Issue by F1ReBRaND** [Lacro59/playnite-gameactivity-plugin#173]
Plugin just open the graphs but takes too long to load when it should be really quick load, and doesn't show the whole data activity
![imagen_2022-10-14_183801280](https://user-images.githubusercontent.com/115851401/195963274-138c1f0c-12d9-452f-b166-741071deee96.png)
![imagen_2022-10-14_190049595](https://user-images.githubusercontent.com/115851401/195963971-02e54897-18a6-437e-aa2b-84bc71c64c1d.png)

Notified me with a message "Object reference not set to an instance of an object" (language keeps in Spanish even after changing to English in Playnite)
![imagen_2022-10-14_182738926](https://user-images.githubusercontent.com/115851401/195962972-1f5bc681-8399-45c0-ba7a-ec1ea676773f.png)
 and then with "do you want to create a log package?"
 
 
[MyLog.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/9790937/MyLog.zip)

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-plugincommon/commit/555c31df06eb9b451dcfd37d295d2d2d5092f955
