### ISSUE TITLE
Delete session?

### ISSUE THREAD

**Issue by OsoaGH** [Lacro59/playnite-gameactivity-plugin#175]
Sorry if I'm being blind or an idiot, but I can't seem to find an option to delete a session. If it doesn't exist, would it be possible to add it or give instructions on how to manually delete a session?

**Comment by OsoaGH** [comment]
That button is simply not there for me, I'm trying to remove the 2h 46m session:
![image](https://user-images.githubusercontent.com/33041004/208484891-f7b40a70-6fe8-4d83-bd91-cbe3863bd73a.png)

**Comment by OsoaGH** [comment]
@Lacro59

**Comment by Lacro59** [comment]
[playnite-gameactivity-plugin_3_0_1.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/10347290/playnite-gameactivity-plugin_3_0_1.zip)

**Comment by OsoaGH** [comment]
Thanks, this has fixed it for me
