### ISSUE TITLE
Object reference not set to an instance of an object notification.

### ISSUE THREAD

**Issue by Chuckable-Nerd** [Lacro59/playnite-gameactivity-plugin#182]
When I open playnite I always get a notification saying "Object reference not set to an instance of an object."

The program seems to run correctly other than that so not really sure why it is happening. I took a playnite backup and restored on a different OS which is where I am getting this error so maybe that is why it is happening? 

Either way I have added the logs that are created when I click on the notification in the hopes it will help figure out the issue. 
I have also tried uninstalling and reinstalling the extension but it continued to happen after that too. 

Thanks for looking into it! 

[extensions.log](https://github.com/Lacro59/playnite-gameactivity-plugin/files/10541882/extensions.log)
[playnite.log](https://github.com/Lacro59/playnite-gameactivity-plugin/files/10541884/playnite.log)

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-plugincommon/commit/796c76a0d576453cad3f641242b35b6c826cb065

**Comment by jaceneliot** [comment]
I have the same issue i don't know that to do...
