### ISSUE TITLE
Can't monitor GPU usage and FPS at the same time [HWiNFO]

### ISSUE THREAD

**Issue by Wolokin** [Lacro59/playnite-gameactivity-plugin#190]
After setting up logging with HWiNFO gadget I noticed that GPU Usage wasn't being logged (was stuck at 0). I checked the HWiNFO registry entries and they seem fine:
![obraz](https://github.com/Lacro59/playnite-gameactivity-plugin/assets/56364893/366d3d28-955e-42ff-af7c-1c19075655b4)
and they correspond to the indices I've set:
![obraz](https://github.com/Lacro59/playnite-gameactivity-plugin/assets/56364893/4575a244-f09c-4046-ae1b-35640d4ab375)
The data looks like this however (notice GPU Usage sitting at 0%):
![obraz](https://github.com/Lacro59/playnite-gameactivity-plugin/assets/56364893/c95100ba-45af-4b86-a404-ab9765c6302f)

While messing around I found out that if I disable reporting FPS to gadget in HWiNFO, GPU Usage starts being monitored correctly.

After jumping to the 'Games Activities' page, it seems that neither CPU/GPU Temperature nor Power is being monitored correctly either.

Any idea what might be the problem?

**Comment by OtakuMuch** [comment]
Did you fix this? I use HWInfo as well and only CPU and RAM usage works for me, set it up correctly as well but not that informed on this to be 100% sure... If you have solved it, please help me as well @-@
![image](https://github.com/Lacro59/playnite-gameactivity-plugin/assets/107497674/4fe2f8a8-0f2b-4549-bf00-08d374901413)
![image](https://github.com/Lacro59/playnite-gameactivity-plugin/assets/107497674/21970a1f-6d11-44e3-bd09-799ebb178ce8)
![image](https://github.com/Lacro59/playnite-gameactivity-plugin/assets/107497674/7d8a858d-8513-49b7-aad9-cf9a2324454e)
