### ISSUE TITLE
Transfering data erased it instead

### ISSUE THREAD

**Issue by UjCbFwtBayFM** [Lacro59/playnite-gameactivity-plugin#200]
Using GameActivity 3.10 with Playnite 10.19.
I noticed I had a duplicate of game in my library, with playtime data split between the two.
Used the "Transfer plugin data" option in "Extensions > GameActivity" menu, both games had their GameActivity data erased.
Does the plugin have backups?

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-plugincommon/commit/07f1eb1b14074659a25fd72247b1a69bc00c7a54
