### ISSUE TITLE
Import Playtime from Steam

### ISSUE THREAD

**Issue by szwenger** [Lacro59/playnite-gameactivity-plugin#209]
I was wondering if it is possible to import the already existing playtime from Steam. I tried many methods but none worked sadly.

**Comment by Lacro59** [comment]
This isn't the purpose of the plugin.
The playtime import is possible with the Steam library: 
https://github.com/JosefNemec/PlayniteExtensions/wiki/Steam-troubleshooting#play-time-is-not-being-imported
