### ISSUE TITLE
[Feature Request] Get Data from libraries play times

### ISSUE THREAD

**Issue by greggameplayer** [Lacro59/playnite-gameactivity-plugin#24]
It would be awesome to have play times from the differents libraries inside your plugin, because the official libraries implementations show play time but it doesn't appear in your extension.

**Comment by Lacro59** [comment]
What play time are you talking about?
The plugin view show many playtime:
![image](https://user-images.githubusercontent.com/124054/100479048-608a7080-30ed-11eb-8237-233a28202302.png)

**Comment by greggameplayer** [comment]
Yes but it doesn't import the official playtime from platforms automatically

**Comment by Lacro59** [comment]
Official playtime is the total playtime regardless of when it was played.
It's too limited.

The plugin saves one game time per session depending on the date it was played.
This to display a game time per day, week, month, ...

You can view a total playtime by game on statistics view.

**Comment by greggameplayer** [comment]
So it can't retrieve the already registered playtime from steam for example ?

**Comment by shakeyourbunny** [comment]
It is still missing the play activity from my Steam and other libraries for my games.

Without it, it is a bit useless, if it just tracks the games which are not tied to libraries or don't have game time...

**Comment by shakeyourbunny** [comment]
Any news on this?

**Comment by Lacro59** [comment]
> So it can't retrieve the already registered playtime from steam for example ?
I'm not even sure Steam is recording the time of different game sessions.

**Comment by Lacro59** [comment]
> It is still missing the play activity from my Steam and other libraries for my games.
> 
> Without it, it is a bit useless, if it just tracks the games which are not tied to libraries or don't have game time...

No time of your gaming sessions is recorded?

**Comment by AB1908** [comment]
Indeed, the various launchers don't store game activity. Some launchers don't seem to store time played at all. To my knowledge, this is the only way to see a dashboard of what you've played, short of a system-wide time tracker like https://activitywatch.net.
