### ISSUE TITLE
Crash after clicking on previous time period button 

### ISSUE THREAD

**Issue by sengtsan** [Lacro59/playnite-gameactivity-plugin#30]
Action taken:
Open gameactivity window to view game data. 
Click on backward arrow to view data for previous time period

result: crash

eror report and screenshot of where error occured attached. 
Best regards,

[error.log](https://github.com/Lacro59/playnite-gameactivity-plugin/files/6080318/error.log)
![Untitled](https://user-images.githubusercontent.com/63714826/109897948-5c8d6200-7c8b-11eb-820e-24f31315347a.jpg)

**Comment by Lacro59** [comment]
Have you try with the new version on Playnite9 beta?

**Comment by sengtsan** [comment]
Thanks for getting in touch. Not yet. If i do i will let you know.
All the best,

**Comment by Lacro59** [comment]
Have you try with the new version?

**Comment by sengtsan** [comment]
Works perfectly now! Also love the way the platform icons display.
Beautiful!

You a god among men :)
