### ISSUE TITLE
Feature request: ability to change displayed date format

### ISSUE THREAD

**Issue by sengtsan** [Lacro59/playnite-gameactivity-plugin#31]
the plugin currently displays dates as MM/DD/YYYY format

can the plugin enable the option to change the displayed format, e.g. DD/MM/YY?

Best Regards,

**Comment by Lacro59** [comment]
The plugin displays the date in the format of the local machine.
Normally, Playnite does the same.

Is it consistent to have different formats between the application and the plugin?

**Comment by sengtsan** [comment]
Ha! You are right, after a windows update I had been switched back to US
date format and it was in Playnite I first noticed it. Scratch that
request.
Thanks again.

I have another suggestion regarding the formatting of the display, but will
post as a seperate entry on Github.

Thanks for your hard work and making Playnite better
