### ISSUE TITLE
Playnite 9 Beta : Plugin didn't load correctly

### ISSUE THREAD

**Issue by NoAccount1** [Lacro59/playnite-gameactivity-plugin#41]
On the Playnite 9 Beta, the plugin won't load.
I tried to install it from the plugin manager and from github but it doesn't work anymore

![image](https://user-images.githubusercontent.com/74969657/133572979-db9b2bd8-a453-4a26-a7f2-cc9f8d685379.png)

The log wich concern the extension : 
```log
16-09 09:51:40.746|ERROR|ExtensionFactory:Failed to load plugin: GameActivity
System.IO.IOException: Impossible de créer un fichier déjà existant.

   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   à CommonPluginsShared.PlayniteExtended.PluginExtended`2.TransfertOldDatabase() dans D:\GitHub\Lacro59\playnite-gameactivity-plugin\source\playnite-plugincommon\CommonPluginsShared\PlayniteExtended\PluginExtended.cs:ligne 50
   à CommonPluginsShared.PlayniteExtended.PluginExtended`2..ctor(IPlayniteAPI api) dans D:\GitHub\Lacro59\playnite-gameactivity-plugin\source\playnite-plugincommon\CommonPluginsShared\PlayniteExtended\PluginExtended.cs:ligne 30
   à GameActivity.GameActivity..ctor(IPlayniteAPI api) dans D:\GitHub\Lacro59\playnite-gameactivity-plugin\source\GameActivity.cs:ligne 40
```

**Comment by Lacro59** [comment]
Can you try with the last release (v2.0.1)?

**Comment by NoAccount1** [comment]
The extension seems to load but doesn't do anything (doesn't show up in the sidebar and in the extensions menu)

![image](https://user-images.githubusercontent.com/74969657/133588553-6f3e817f-befc-4054-b805-af5eb35dc5e1.png)
![image](https://user-images.githubusercontent.com/74969657/133588562-9bff6dbd-28a4-4df6-a801-585312a28eea.png)
![image](https://user-images.githubusercontent.com/74969657/133588581-3b8239c6-4d65-4360-82e9-ad0b236bfaf5.png)

**Comment by NoAccount1** [comment]
After another reloading, the extension still doesn't start with the same error

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-plugincommon/commit/b1359a62c504687fe21989a097b7b2028d98bc18
