### ISSUE TITLE
GameActivity#Common:File C:\...ListExtendStyle.xaml not find - log error

### ISSUE THREAD

**Issue by darklinkpower** [Lacro59/playnite-gameactivity-plugin#44]
![image](https://user-images.githubusercontent.com/1389286/135537594-23cb2d62-9e1c-4372-98ef-2fff1ac8bda9.png)

```
30-09 16:32:35.997|WARN |GameActivity#Common:File C:\Games\Playnite\Extensions\playnite-gameactivity-plugin\Resources\Controls\ListExtendStyle.xaml not find
```

[extensions.log](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7262829/extensions.log)

**Comment by Lacro59** [comment]
fixed with the next release
