### ISSUE TITLE
[Feature Request] Multiple action showing

### ISSUE THREAD

**Issue by Ayokx** [Lacro59/playnite-gameactivity-plugin#47]
I do Mario 64 Speedrunning and would like to see in Game Activity what type of speedruns I am doing using the play actions.

Have these play action :
![123](https://user-images.githubusercontent.com/92641740/138130694-2ddbf360-75d0-4891-bccd-3d3982ce6a9a.png)

Show up here : 
![456](https://user-images.githubusercontent.com/92641740/138130878-d2e855d7-032b-4124-b16a-2a0a93229478.png)

It would be to know how much I have played which category?
I looked and didn't find how to do it so is it possible to add this feature or tell me how to do it if it already exists please.

**Comment by Lacro59** [comment]
Wait this: https://github.com/JosefNemec/Playnite/issues/2637
