### ISSUE TITLE
Version 2.1.2: Source entries in settings bug

### ISSUE THREAD

**Issue by Andei** [Lacro59/playnite-gameactivity-plugin#50]
With every restart I get more entries

![Playnite DesktopApp_zoXLIXKEYy](https://user-images.githubusercontent.com/7351090/140559495-cf633521-73fc-4de0-82a9-28fbe8af5611.png)

**Comment by Lacro59** [comment]
Can you delete your plugin configuration?
here:
![image](https://user-images.githubusercontent.com/124054/140653510-ebfbdd28-d0b3-4843-9ab3-986d854c23cf.png)

**Comment by Andei** [comment]
Playnite still doubled
![Playnite DesktopApp_zckFGkwotp](https://user-images.githubusercontent.com/7351090/140659737-e0ff6394-530d-4fd4-8752-e6b662836f52.png)
