### ISSUE TITLE
[Suggestion] Make the wiki more clear for MSI afterburner

### ISSUE THREAD

**Issue by imrayya** [Lacro59/playnite-gameactivity-plugin#54]
For the following [link](https://github.com/Lacro59/playnite-gameactivity-plugin/wiki/How-to-use-log-with-MSI-Afterburner) on how to activate MSI Afterburner isn't enough to actually make it play well with this plug in, at least in my use case. These are the step I used to actually enable it.

3. Open Afterburner
4. Go to Settings
5. Open the tab of monitoring
6. Click on the 3 little dots labeled "Activate hardware monitoring graphs"
7. Activate the following plug ins (not sure which is actually relevant) "CPU.dll, GPU.dll, PerfCounter.dll" and press OK
8. Enable all FPS and Temp relevant graphs
9. Finally click Apply or OK
10. Configure plugin in Playnite settings menu

**Comment by Lacro59** [comment]
Thanks for your feedback.
