### ISSUE TITLE
Index was out of range error

### ISSUE THREAD

**Issue by aarish-github** [Lacro59/playnite-gameactivity-plugin#6]
Getting this error repeatedly on Playnite 7.7 portable version. Tried re-installing the extension multiple times.

![image](https://user-images.githubusercontent.com/17380542/86085379-a26ea680-babc-11ea-827e-a169ebd52b7a.png)

**Comment by aarish-codev** [comment]
@Lacro59  Thanks for the quick fix, loving your application.

**Comment by Lacro59** [comment]
@aarish-codev Thanks :)
