### ISSUE TITLE
Game time doubling

### ISSUE THREAD

**Issue by flzubuduuz** [Lacro59/playnite-gameactivity-plugin#60]
Hi, I installed GameActivity yesterday and noticed that my gametime according to GameActivity is always twice the time I have actually played. As you can see in the screenshot below, I played two sessions of a game (one was 1 minute long, the other one was 46 minutes long), and each was counted twice, with the total time on Steam also being double what it should be. This has happened for every game I have opened since installing GameActivity.

(p.s. I'm currently running Windows 11, I don't know if that might have something to do with this issue)

![gameactivity doubling](https://user-images.githubusercontent.com/80221875/141668105-d1aa47ba-eb58-447e-9244-975156105670.png)

**Comment by Andei** [comment]
Same for me.

Started MP3 for checking tracking with Rockstar launcher.
![Playnite DesktopApp_mUKPKXdayj](https://user-images.githubusercontent.com/7351090/141675947-b04233a5-cc12-4650-bd4e-2283c57faca4.png)

Restart PN
![Playnite DesktopApp_uDRqlio1Vo](https://user-images.githubusercontent.com/7351090/141675983-1977b10c-bc28-4606-a88c-a87ceb27e106.png)

Checking previous game
![Playnite DesktopApp_7Dn6zwrsQa](https://user-images.githubusercontent.com/7351090/141676073-da794617-6289-441f-85af-afcae0f85cd6.png)

**Comment by DivineBladeofDarkness** [comment]
Same problem here too. I had to downgrade to 2.12 version which doesn't have this problem

**Comment by chocolatechipcats** [comment]
> (p.s. I'm currently running Windows 11, I don't know if that might have something to do with this issue)

I am on Windows 10 and have the same issue (as well as another [time tracking issue](https://github.com/Lacro59/playnite-gameactivity-plugin/issues/61), which sadly was not fixed by reverting to 2.1.2).

**Comment by HerrKnarz** [comment]
It seems that every time I play a game and restart playnite all logged times of that game are doubled. For example my play time for Mass Effect Legendary Edition allready was on 11 hours for today and after a restart it jumped to 22 hours. After restarting Playnite without playing a game, the times stayed the same. Because of this bug I now have 227 hours of play time on 14th of november alone :D
![screenshot](https://user-images.githubusercontent.com/40741234/141697392-01eca510-5e73-46b0-8630-e753420addf9.png)

**Comment by sengtsan** [comment]
> It seems that every time I play a game and restart playnite all logged times of that game are doubled. For example my play time for Mass Effect Legendary Edition allready was on 11 hours for today and after a restart it jumped to 22 hours. After restarting Playnite without playing a game, the times stayed the same. Because of this bug I now have 227 hours of play time on 14th of november alone :D 

I am experiencing the same issue.

**Comment by Quayyy** [comment]
fixed now, thank you!
