### ISSUE TITLE
Time tracking fails when multiple games running

### ISSUE THREAD

**Issue by chocolatechipcats** [Lacro59/playnite-gameactivity-plugin#61]
Playnite 9.6, plugin version 2.2.

I've noticed that time tracking sometimes fails when multiple games are running, and gets recorded as "not played." Steps to replicate:

1. Launch a game.
2. Launch a second game.
3. Exit the first game, or tell Playnite to stop monitoring it.
4. Check the game activity of the first game. It remains as "not played."

![image](https://user-images.githubusercontent.com/47759676/141683876-214bd629-f7a3-4afc-b937-973e5941f549.png)

If you need any more info I can try to provide.

Thank you.

**Comment by Lacro59** [comment]
Are you still having issues with the latest version?

**Comment by chocolatechipcats** [comment]
Yes, but this time it's changed. 

This time I opened GameA, and then GameB. Then I closed them in the same order. This time, GameA didn't even record anything (looking at the associated json file confirms), though the extended theme button shows "Not Played."
