### ISSUE TITLE
[Feature request] Add the option to manually edit entries

### ISSUE THREAD

**Issue by BanCrash** [Lacro59/playnite-gameactivity-plugin#64]
(Based on my comment on #55, I think this should be a different Feature request issue).

Hi, currently we can edit the total play time in Playnite but if we use this extension play time and individual entries values will not be consistent. So I think could be useful to have a manual editor to be able to also change the individual entries generated by this extension.

Suggestion:

1. Add a new option, similar to remove individual entries, to manually edit one entry.
2. (Optional) Add an option to also manually add individual entries from 0, so we can manage all data related to the play time.

**Comment by BanCrash** [comment]
Hi @Lacro59 , thanks for adding this feature, I've saw the icon for adding a new entry, but I don't know how can I edit an already existing one.

**Comment by Lacro59** [comment]
For the next release
https://github.com/Lacro59/playnite-gameactivity-plugin/commit/bf54dedfaa473c2a1b73bc3ad13c1f5cc1d509c7

**Comment by BanCrash** [comment]
> For the next release [bf54ded](https://github.com/Lacro59/playnite-gameactivity-plugin/commit/bf54dedfaa473c2a1b73bc3ad13c1f5cc1d509c7)

Perfect, thanks!

**Comment by Dasnap** [comment]
Just to jump in awkwardly here, I'm still struggling to find an edit button. I currently have a few duplicate entries I want to remove but I'm a little lost.

**Comment by BanCrash** [comment]
> Just to jump in awkwardly here, I'm still struggling to find an edit button. I currently have a few duplicate entries I want to remove but I'm a little lost.

@Dasnap Probably you have to horizontally scroll to find the edit button: 
![image](https://user-images.githubusercontent.com/11770760/164076249-277e71ff-2e39-4732-bda8-c39626de3ea7.png)

![image](https://user-images.githubusercontent.com/11770760/164076357-c2900751-9619-4212-ac02-2032aa3112fb.png)
