### ISSUE TITLE
Playnite completely freezes on startup with v2.3

### ISSUE THREAD

**Issue by darklinkpower** [Lacro59/playnite-gameactivity-plugin#67]
![image](https://user-images.githubusercontent.com/1389286/142739203-26f47827-8362-4bde-b14f-e2384ef71214.png)

Extensions.log

```
20-11 13:47:57.058|WARN |GameActivity#PluginDatabaseObject`3:Duplicate items (42439) in Rocket League
```

**Comment by darklinkpower** [comment]
Game json file
[2b4c6925-ee7a-406e-90ef-30a38a4081b7.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7575149/2b4c6925-ee7a-406e-90ef-30a38a4081b7.zip)

**Comment by felixkmh** [comment]
It's a deadlock. https://github.com/Lacro59/playnite-gameactivity-plugin/blob/7ee1ef7dc620381dd19c60b2d3f2bd2c54e74e37/source/Services/ActivityDatabase.cs#L28 Is supposed to set ```IsLoaded``` to ```true```, but in some cases https://github.com/Lacro59/playnite-gameactivity-plugin/blob/7ee1ef7dc620381dd19c60b2d3f2bd2c54e74e37/source/Services/ActivityDatabase.cs#L48 is called which leads to 
https://github.com/Lacro59/playnite-plugincommon/blob/0f08999d45fdc3f4e5fa26e6441accf081e53773/CommonPluginsShared/Collections/PluginDatabaseObject.cs#L549
 being called, which is then also wating for ```IsLoaded``` to be set to ```true``` which can never happen, causing the deadlock.

**Comment by Lacro59** [comment]
@felixkmh I added this for fix this: https://github.com/Lacro59/playnite-successstory-plugin/issues/192
For me, the problem is here: https://github.com/Lacro59/playnite-gameactivity-plugin/blob/7ee1ef7dc620381dd19c60b2d3f2bd2c54e74e37/source/Services/ActivityDatabase.cs#L38
This treatment can be long and blocking.
