### ISSUE TITLE
New update crashes Playnite

### ISSUE THREAD

**Issue by HairyHook** [Lacro59/playnite-gameactivity-plugin#68]
Playnite prompted to update the addon to 2.3.1, and  after the restart, the whole program freezes and refuses to start. It only starts successfully after deleting the gameactivity extension folder. This is the only activity that had to be updated and I have tried to update 3 times with same results.

**Comment by Lacro59** [comment]
Can you post the crash report?

**Comment by HairyHook** [comment]
Sure. What's the exact file name and path that you need? Thanks for the quick answer.

**Comment by sengtsan** [comment]
I have the same issue. Can send a crash report too, but have the same question as HairyHook. 


Thank you,

**Comment by Lacro59** [comment]
> Sure. What's the exact file name and path that you need? Thanks for the quick answer.
When Playnite crash, you have a buton to generate log report file.

**Comment by HairyHook** [comment]
Crash might be a weird way to explain the behavior. After restarting with 2.3.1, Playnite loads the icon, and it gets frozen there. Briefly I see a Loading Game Library message but the app icon is not displayed in the notification tray (vs when it loads successfully). It's more like a "unable to fully boot" behavior. For now I deleted the game activity extension folder and I can boot into PN. No crash log or prompt.

**Comment by Lacro59** [comment]
Can you try this version?
[playnite-gameactivity-plugin_2_3_1.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7576851/playnite-gameactivity-plugin_2_3_1.zip)
And post the extension.log in %AppData%\Playnite or in Playnite folder (if portable version).

**Comment by HairyHook** [comment]
Just tried, same behavior. Playnite process is running, window doesn't open and icon is not in the notification tray.

Playnite.log after installing the extension:

21-11 13:00:54.467|INFO |ExtensionInstaller:Installing extenstion/theme C:\Users\Administrator\Downloads\playnite-gameactivity-plugin_2_3_1\playnite-gameactivity-plugin_2_3_1.pext
21-11 13:00:54.654|INFO |ExtensionInstaller:Installed extension C:\Users\Administrator\Downloads\playnite-gameactivity-plugin_2_3_1\playnite-gameactivity-plugin_2_3_1.pext
21-11 13:00:55.377|INFO |PlayniteApplication:Application started from 'D:\Playnite'
21-11 13:00:56.995|INFO |ExtensionFactory:Loaded plugin: AmazonGames library integration, version 2.3
21-11 13:00:57.001|INFO |ExtensionFactory:Loaded plugin: Battle.net library integration, version 2.3
21-11 13:00:57.021|INFO |ExtensionFactory:Loaded plugin: Epic Store library integration, version 2.5
21-11 13:00:57.041|INFO |ExtensionFactory:Loaded plugin: Extra Metadata Loader, version 1.20
21-11 13:00:57.064|INFO |ExtensionFactory:Loaded plugin: DuplicateHider, version 3.7.1
21-11 13:00:57.064|INFO |ExtensionFactory:Loaded plugin: Game Pass Catalog Browser, version 2.5
21-11 13:00:57.064|INFO |ExtensionFactory:Loaded plugin: GOG library integration, version 2.4
21-11 13:00:57.083|INFO |ExtensionFactory:Loaded plugin: IGDB metadata provider, version 2.3
21-11 13:00:57.083|INFO |ExtensionFactory:Loaded plugin: Ludusavi, version 0.6.0
21-11 13:00:57.094|INFO |ExtensionFactory:Loaded plugin: Origin library integration, version 2.3
21-11 13:00:57.190|INFO |ExtensionFactory:Loaded plugin: GameActivity, version 2.3.1
21-11 13:00:57.248|INFO |ExtensionFactory:Loaded plugin: HowLongToBeat, version 2.4
21-11 13:00:57.287|INFO |ExtensionFactory:Loaded plugin: IsThereAnyDeal, version 2.0
21-11 13:00:57.367|INFO |ExtensionFactory:Loaded plugin: ThemeModifier, version 2.2.3
21-11 13:00:57.376|INFO |ExtensionFactory:Loaded plugin: PlayStation library integration, version 2.12
21-11 13:00:57.376|INFO |ExtensionFactory:Loaded plugin: Review Viewer, version 2.11
21-11 13:00:57.398|INFO |ExtensionFactory:Loaded plugin: Steam library integration, version 2.3
21-11 13:00:57.398|INFO |ExtensionFactory:Loaded plugin: Universal Steam Metadata, version 2.3
21-11 13:00:57.419|INFO |ExtensionFactory:Loaded plugin: Uplay library integration, version 2.2
21-11 13:00:57.430|INFO |ExtensionFactory:Loaded plugin: Xbox library integration, version 2.3
21-11 13:00:57.830|INFO |ExtensionFactory:Loaded script extension: D:\Playnite\Extensions\Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e\ExtraMetadataTools.psm1, version 2.7
21-11 13:00:57.830|INFO |ExtensionFactory:Loaded script extension: D:\Playnite\Extensions\LibraryExporterPS_Builtin\LibraryExporter.psm1, version 2.0
21-11 13:00:57.849|INFO |ExtensionFactory:Loaded script extension: D:\Playnite\Extensions\Search_Collection\SearchCollection.psm1, version 2.6
21-11 13:00:57.949|DEBUG|WindowFactory:Show window Playnite.DesktopApp.Windows.MainWindowFactory
21-11 13:00:57.949|DEBUG|WindowFactory:Opening window that was closed previously Playnite.DesktopApp.Windows.MainWindowFactory
21-11 13:00:58.192|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory
21-11 13:00:58.466|INFO |GameDatabase:Opening db D:\Playnite\library
21-11 13:00:58.699|WARN |ExecutionTimer:--- Timer 'DatabaseLoadCollections', 231 ms to complete.
21-11 13:00:58.710|INFO |DatabaseStats:Completely recalculating database statistics...
21-11 13:00:58.720|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory, True.

extension.log:

21-11 12:59:57.638|DEBUG|AmazonGamesLibrary#AmazonGamesLibrary:Found 1 installed Amazon games.
21-11 13:00:02.254|DEBUG|AmazonGamesLibrary#AmazonGamesLibrary:Found 300 library Amazon games.
21-11 13:00:02.296|DEBUG|BattleNetLibrary#BattleNetLibrary:Found 0 installed Battle.net games.
21-11 13:00:05.021|WARN |BattleNetLibrary#BattleNetLibrary:Unknown game found on the account: Destiny 2/1146311730, skipping import.
21-11 13:00:05.270|DEBUG|BattleNetLibrary#BattleNetLibrary:Found 6 library Battle.net games.
21-11 13:00:05.288|DEBUG|EpicLibrary#EpicLibrary:Found 2 installed Epic games.
21-11 13:00:06.982|DEBUG|EpicLibrary#EpicLibrary:Found 200 library Epic games.
21-11 13:00:07.008|DEBUG|GogLibrary#GogLibrary:Found 0 installed GOG games.
21-11 13:00:09.432|DEBUG|GogLibrary#GogLibrary:Found 99 library GOG games.
21-11 13:00:09.438|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/Origin.OFR.50.0004288/en_US.
21-11 13:00:09.684|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/Origin.OFR.50.0003795/en_US.
21-11 13:00:09.910|DEBUG|OriginLibrary#OriginLibrary:Found 2 installed Origin games.
21-11 13:00:11.159|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/Origin.OFR.50.0003112/en_IE?country=IE.
21-11 13:00:11.706|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/Origin.OFR.50.0003112/en_US.
21-11 13:00:11.851|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/Origin.OFR.50.0000357/en_IE?country=IE.
21-11 13:00:12.281|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/Origin.OFR.50.0000357/en_US.
21-11 13:00:12.514|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/DR:231812900/en_IE?country=IE.
21-11 13:00:12.942|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/DR:231812900/en_US.
21-11 13:00:13.163|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/Origin.OFR.50.0001131/en_IE?country=IE.
21-11 13:00:13.582|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/Origin.OFR.50.0001131/en_US.
21-11 13:00:13.612|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/OFB-EAST:1000017/en_IE?country=IE.
21-11 13:00:14.033|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/OFB-EAST:1000017/en_US.
21-11 13:00:14.273|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/OFB-EAST:50499/en_IE?country=IE.
21-11 13:00:14.686|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/OFB-EAST:50499/en_US.
21-11 13:00:14.906|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/Origin.OFR.50.0001443/en_IE?country=IE.
21-11 13:00:15.346|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/Origin.OFR.50.0001443/en_US.
21-11 13:00:15.622|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/Origin.OFR.50.0000461/en_IE?country=IE.
21-11 13:00:16.091|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/Origin.OFR.50.0000461/en_US.
21-11 13:00:16.315|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/Origin.OFR.50.0004662/en_IE?country=IE.
21-11 13:00:16.757|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/Origin.OFR.50.0004662/en_US.
21-11 13:00:16.980|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/Origin.OFR.50.0000583/en_IE?country=IE.
21-11 13:00:17.450|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/Origin.OFR.50.0000583/en_US.
21-11 13:00:17.676|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/OFB-EAST:109552419/en_IE?country=IE.
21-11 13:00:18.093|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/OFB-EAST:109552419/en_US.
21-11 13:00:18.318|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/OFB-EAST:109547468/en_IE?country=IE.
21-11 13:00:18.750|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/OFB-EAST:109547468/en_US.
21-11 13:00:19.016|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/DR:232511600/en_IE?country=IE.
21-11 13:00:19.607|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/DR:232511600/en_US.
21-11 13:00:19.945|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/OFB-EAST:49753/en_IE?country=IE.
21-11 13:00:20.673|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/OFB-EAST:49753/en_US.
21-11 13:00:21.008|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/DR:235663500/en_IE?country=IE.
21-11 13:00:21.507|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/DR:235663500/en_US.
21-11 13:00:22.387|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/Origin.OFR.50.0001895/en_IE?country=IE.
21-11 13:00:22.889|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/Origin.OFR.50.0001895/en_US.
21-11 13:00:23.184|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/Origin.OFR.50.0001452/en_IE?country=IE.
21-11 13:00:23.892|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/Origin.OFR.50.0001452/en_US.
21-11 13:00:24.415|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/OFB-EAST:48217/en_IE?country=IE.
21-11 13:00:24.959|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/OFB-EAST:48217/en_US.
21-11 13:00:25.154|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/OFB-EAST:109552105/en_IE?country=IE.
21-11 13:00:25.697|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/OFB-EAST:109552105/en_US.
21-11 13:00:26.293|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/Origin.OFR.50.0000557/en_IE?country=IE.
21-11 13:00:26.946|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/Origin.OFR.50.0000557/en_US.
21-11 13:00:27.214|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/Origin.OFR.50.0002759/en_IE?country=IE.
21-11 13:00:27.924|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/Origin.OFR.50.0002759/en_US.
21-11 13:00:28.397|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/OFB-EAST:51582/en_IE?country=IE.
21-11 13:00:28.981|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/OFB-EAST:51582/en_US.
21-11 13:00:29.373|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/OFB-EAST:109548462/en_IE?country=IE.
21-11 13:00:29.822|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/OFB-EAST:109548462/en_US.
21-11 13:00:30.489|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/Origin.OFR.50.0004660/en_IE?country=IE.
21-11 13:00:31.071|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/Origin.OFR.50.0004660/en_US.
21-11 13:00:31.244|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/OFB-EAST:60108/en_IE?country=IE.
21-11 13:00:31.819|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/OFB-EAST:60108/en_US.
21-11 13:00:32.126|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/Origin.OFR.50.0002694/en_IE?country=IE.
21-11 13:00:32.993|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/Origin.OFR.50.0002694/en_US.
21-11 13:00:33.394|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/OFB-EAST:56186/en_IE?country=IE.
21-11 13:00:34.387|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/OFB-EAST:56186/en_US.
21-11 13:00:34.621|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/Origin.OFR.50.0001928/en_IE?country=IE.
21-11 13:00:35.241|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/Origin.OFR.50.0001928/en_US.
21-11 13:00:35.632|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/Origin.OFR.50.0001057/en_IE?country=IE.
21-11 13:00:36.779|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/Origin.OFR.50.0001057/en_US.
21-11 13:00:37.001|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/DR:225064100/en_IE?country=IE.
21-11 13:00:37.983|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/DR:225064100/en_US.
21-11 13:00:38.272|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/OFB-EAST:46560/en_IE?country=IE.
21-11 13:00:39.142|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/OFB-EAST:46560/en_US.
21-11 13:00:39.789|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/OFB-EAST:56694/en_IE?country=IE.
21-11 13:00:40.579|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/OFB-EAST:56694/en_US.
21-11 13:00:41.122|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/OFB-EAST:49459/en_IE?country=IE.
21-11 13:00:42.176|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/OFB-EAST:49459/en_US.
21-11 13:00:42.689|DEBUG|OriginLibrary#Downloader:Downloading data from https://api2.origin.com/ecommerce2/public/supercat/Origin.OFR.50.0002487/en_IE?country=IE.
21-11 13:00:43.443|DEBUG|OriginLibrary#Downloader:Downloading data from https://api1.origin.com/ecommerce2/public/Origin.OFR.50.0002487/en_US.
21-11 13:00:43.868|DEBUG|OriginLibrary#OriginLibrary:Found 34 library Origin games.
21-11 13:00:46.867|ERROR|SteamLibrary#SteamLibrary:Failed to get information about installed game from: d:\steam\steamapps\appmanifest_489830.acf
System.UnauthorizedAccessException: Access to the path 'd:\steam\steamapps\appmanifest_489830.acf' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at SteamKit2.KeyValue.ReadFileAsText(String filename)
   at SteamLibrary.SteamLibrary.GetInstalledGameFromFile(String path) in E:\Devel\PlayniteExtensions\source\Libraries\SteamLibrary\SteamLibrary.cs:line 81
   at SteamLibrary.SteamLibrary.GetInstalledGamesFromFolder(String path) in E:\Devel\PlayniteExtensions\source\Libraries\SteamLibrary\SteamLibrary.cs:line 128
21-11 13:00:46.887|ERROR|SteamLibrary#SteamLibrary:Failed to get information about installed game from: D:\Steam\steamapps\appmanifest_489830.acf
System.UnauthorizedAccessException: Access to the path 'D:\Steam\steamapps\appmanifest_489830.acf' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at SteamKit2.KeyValue.ReadFileAsText(String filename)
   at SteamLibrary.SteamLibrary.GetInstalledGameFromFile(String path) in E:\Devel\PlayniteExtensions\source\Libraries\SteamLibrary\SteamLibrary.cs:line 81
   at SteamLibrary.SteamLibrary.GetInstalledGamesFromFolder(String path) in E:\Devel\PlayniteExtensions\source\Libraries\SteamLibrary\SteamLibrary.cs:line 128
21-11 13:00:46.887|DEBUG|SteamLibrary#SteamLibrary:Found 18 installed Steam games.
21-11 13:00:47.057|DEBUG|SteamLibrary#SteamLibrary:Found 245 library Steam games.
21-11 13:00:47.065|DEBUG|UplayLibrary#UplayLibrary:Found 3 installed Uplay games.
21-11 13:00:47.247|DEBUG|UplayLibrary#UplayLibrary:Found 45 library Uplay games.
21-11 13:00:47.385|DEBUG|XboxLibrary#XboxAccountClient:Refreshing xbox tokens.
21-11 13:00:49.796|DEBUG|XboxLibrary#XboxLibrary:Found 3 installed Xbox games.
21-11 13:00:49.797|DEBUG|XboxLibrary#XboxLibrary:Found 7 Xbox PC games.
21-11 13:00:51.127|INFO |HowLongToBeat#PlaynitePlugin`1:Task OnLibraryUpdated() - 00:00.00 for 0/0 items

**Comment by Lacro59** [comment]
Can you try this version?
[playnite-gameactivity-plugin_2_3_1.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7577133/playnite-gameactivity-plugin_2_3_1.zip)

**Comment by sengtsan** [comment]
Thank you for the instructions. 

I have attached the extension.log file from the playnite folder after installing and restarting playnite. 

[extensions.log](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7577159/extensions.log)

Object reference not set to an instance of an object error message comes up as before. 

Game Activity data is not correct as before. See image:
![gameactivity](https://user-images.githubusercontent.com/63714826/142779726-12013800-b479-4e93-bc79-2e7ef7809306.jpg)

Thank you,

**Comment by Lacro59** [comment]
Thanks for your feedback.
Can you try this version?
[playnite-gameactivity-plugin_2_3_1.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7577176/playnite-gameactivity-plugin_2_3_1.zip)

**Comment by sengtsan** [comment]
> Thanks for your feedback. Can you try this version? [playnite-gameactivity-plugin_2_3_1.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7577223/playnite-gameactivity-plugin_2_3_1.zip)

Hi, yes, this is the version I installed before generating the extension.log report and taking the screenshot.

**Comment by HairyHook** [comment]
> Thanks for your feedback. Can you try this version? [playnite-gameactivity-plugin_2_3_1.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7577223/playnite-gameactivity-plugin_2_3_1.zip)

This version allows playnite to start, but experiencing same behavior as sengtan. It says it tracked 900 hours this week.

**Comment by Lacro59** [comment]
Can you post your plugin data folder in %AppData%\extensionData\afbb1a0d-04a1-4d0c-9afa-c6e42ca855b4 or Playnite\ExtensionData\afbb1a0d-04a1-4d0c-9afa-c6e42ca855b4 (if portable version)?

**Comment by sengtsan** [comment]
As requested. Thanks.

[afbb1a0d-04a1-4d0c-9afa-c6e42ca855b4.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7579327/afbb1a0d-04a1-4d0c-9afa-c6e42ca855b4.zip)

**Comment by Lacro59** [comment]
Can you try this version?
[playnite-gameactivity-plugin.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7581921/playnite-gameactivity-plugin.zip)

**Comment by sengtsan** [comment]
> Can you try this version? [playnite-gameactivity-plugin.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7581921/playnite-gameactivity-plugin.zip)

I've installed the new plugin. It no longer crashes, but the data displayed is still not correct.

![Untitled](https://user-images.githubusercontent.com/63714826/142907455-4168fd65-1eb0-464b-b3e3-b2001133a461.jpg)

**Comment by HairyHook** [comment]
> Can you try this version? [playnite-gameactivity-plugin.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7581921/playnite-gameactivity-plugin.zip)

I tried as well. "Object reference not set to an instance of an object" still an issue.

**Comment by Lacro59** [comment]
Can you post your extension.log?

**Comment by sengtsan** [comment]
> Can you post your extension.log?
[extensions.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7586612/extensions.zip)

extension with newest plugin version.

**Comment by Lacro59** [comment]
Have you still the issue with the last release?

**Comment by sengtsan** [comment]
> Have you still the issue with the last release?

I'm afraid so.  

On the plus side, the plugin no longer freezes Playnite. The issues that persist are:

- "Object reference not set to an instance of an object" error still occurs

- Game activity time doesn't seem to be getting logged at all for games played recently. 

- There remains a stretch of time where the time logged is incorrect as per earlier screenshots

I have attached the extensions log again in case you'd find it useful:


[extensions.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7614311/extensions.zip)

Thank you,

**Comment by HairyHook** [comment]
> Have you still the issue with the last release?

Same behavior for me too. Clicking on the "Object reference not set to an instance of an object" error asked to generate a log. Attached,
[GameActivity_2021-11-28.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7614624/GameActivity_2021-11-28.zip)

**Comment by HairyHook** [comment]
Lacro,

The new version is working fine, however whatever happened with the previous one corrupted the extension data. I have a backup of the data folder and when trying to copy it to the new extension version, I get hundred and thousands of hours in the graphs. I decided not to use the old data and start from scratch... But if you are aware of any way I can restore the old data, I would really appreciate it. 

Thanks for your help.

**Comment by Lacro59** [comment]
Can you post your plugin data folder in %AppData%\extensionData\afbb1a0d-04a1-4d0c-9afa-c6e42ca855b4 or Playnite\ExtensionData\afbb1a0d-04a1-4d0c-9afa-c6e42ca855b4 (if portable version) dnd your library folder without the files directory ?

**Comment by HairyHook** [comment]
[afbb1a0d-04a1-4d0c-9afa-c6e42ca855b4.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7645316/afbb1a0d-04a1-4d0c-9afa-c6e42ca855b4.zip)
Attached, thanks for looking into it!

**Comment by maicol07** [comment]
I have the same issue. Here is my data folder if you need it:
[afbb1a0d-04a1-4d0c-9afa-c6e42ca855b4.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7648031/afbb1a0d-04a1-4d0c-9afa-c6e42ca855b4.zip)

**Comment by sengtsan** [comment]
> > Have you still the issue with the last release?
> 
> I'm afraid so.
> 
> On the plus side, the plugin no longer freezes Playnite. The issues that persist are:
> 
> * "Object reference not set to an instance of an object" error still occurs
> * Game activity time doesn't seem to be getting logged at all for games played recently.
> * There remains a stretch of time where the time logged is incorrect as per earlier screenshots
> 
> I have attached the extensions log again in case you'd find it useful:
> 
> [extensions.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7614311/extensions.zip)
> 
> Thank you,

I'll add these logs and data folders in case they help. I still get "Object reference not set to an instance of an object" even after latest update. 
[afbb1a0d-04a1-4d0c-9afa-c6e42ca855b4.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7648059/afbb1a0d-04a1-4d0c-9afa-c6e42ca855b4.zip)
[GameActivity_2021-12-03.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7648062/GameActivity_2021-12-03.zip)

**Comment by maicol07** [comment]
@Lacro59 works fine! Thank you!

**Comment by sengtsan** [comment]
> Can you try with the last release?

Hello again,

Using 2.4.3, still getting the following  issues:

- "Object reference not set to an instance of an object" error still occurs
- Game activity time doesn't seem to be getting logged at all for games played recently.
- There remains a stretch of time where the time logged is incorrect as per earlier screenshots

Attached most recent log and data zips:
[afbb1a0d-04a1-4d0c-9afa-c6e42ca855b4.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7652811/afbb1a0d-04a1-4d0c-9afa-c6e42ca855b4.zip)

[GameActivity_2021-12-03.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7652812/GameActivity_2021-12-03.zip)
