### ISSUE TITLE
Genre tab doesn't even open

### ISSUE THREAD

**Issue by LuigiVs** [Lacro59/playnite-gameactivity-plugin#7]
![Annotation 2020-07-01 120116](https://user-images.githubusercontent.com/52753199/86271686-58102700-bb9b-11ea-818c-d4eac7da5441.png)
The genre doesn't even open at all when opening the extension. Just shows the sources data. Changing the month just breaks it and shows this error.
![Annotation 2020-07-01 120117](https://user-images.githubusercontent.com/52753199/86271969-db317d00-bb9b-11ea-984e-f7e3861effeb.png)

**Comment by Lacro59** [comment]
Is it possible to have a extract to **playnite.log**?
This file is in folder _%AppData%\Playnite_ (or in _Playnite_ folder if portable installation).
