### ISSUE TITLE
Time zone issue on total hours by day

### ISSUE THREAD

**Issue by joesp97** [Lacro59/playnite-gameactivity-plugin#74]
In the screenshot below it said I have total 2 hours and 20 minutes playtime today.
![image](https://user-images.githubusercontent.com/9094451/143553468-5f07940e-44ff-419a-94cb-24eb81802590.png)
But seeing the game list it is definitely more than that. 
Total hours by day only sums the last 2 session which is later than 7 am (I live in UTC +7).
So I guess that is a time zone issue but only for the total hours by day.

**Comment by Lacro59** [comment]
Can you try this version?
[playnite-gameactivity-plugin.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7612395/playnite-gameactivity-plugin.zip)

**Comment by joesp97** [comment]
> Can you try this version? [playnite-gameactivity-plugin.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7612395/playnite-gameactivity-plugin.zip)

That works

**Comment by mczolton** [comment]
It appears release 2.5 has reintroduced this bug. In release 2.4.3, the hours-by-day graph correctly indicates the date of the logged play sessions. In releases 2.5 and 2.5.1, the hours-by-day graph incorrectly indicates the date of the logged play sessions. In my case, the date of the play session in the graph is one day begins the actual play session. 

Release 2.4.3 with correct hours-by-day graph

![2 4 3](https://user-images.githubusercontent.com/482446/151586328-446453ad-bb98-438d-a811-b029356b68db.png)

Release 2.5.1 with incorrect hours-by-day graph

![2 5 1](https://user-images.githubusercontent.com/482446/151586098-a3851828-2267-4451-8771-a192df8493fc.png)

Playnite 9.15
Windows 10 (19044.1466)
