### ISSUE TITLE
GA 2.4: Crash with Start Page enabled

### ISSUE THREAD

**Issue by Andei** [Lacro59/playnite-gameactivity-plugin#75]
`28-11 21:04:26.198|ERROR|PlayniteApplication:Unhandled exception occured.
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei LiveCharts.Wpf.Components.ChartUpdater.UpdateFrequency(TimeSpan freq) in c:\Users\btord\Documents\Projects\LiveCharts\WpfView\Components\ChartUpdater.cs:Zeile 69.
   bei LiveCharts.Wpf.Charts.Base.Chart.UpdateChartFrequency(DependencyObject o, DependencyPropertyChangedEventArgs e) in c:\Users\btord\Documents\Projects\LiveCharts\WpfView\Charts\Base\Chart.cs:Zeile 1446.
   bei System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   bei System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   bei System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   bei System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   bei System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   bei System.Windows.Data.BindingExpression.ScheduleTransfer(Boolean isASubPropertyChange)
   bei MS.Internal.Data.ClrBindingWorker.NewValueAvailable(Boolean dependencySourcesChanged, Boolean initialValue, Boolean isASubPropertyChange)
   bei MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   bei MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
   bei MS.Internal.Data.PropertyPathWorker.OnPropertyChanged(Object sender, PropertyChangedEventArgs e)
   bei System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   bei System.ComponentModel.PropertyChangedEventManager.OnPropertyChanged(Object sender, PropertyChangedEventArgs args)
   bei System.Collections.Generic.ObservableObject.OnPropertyChanged(String name) in C:\projects\playnite\source\PlayniteSDK\Collections\ObservableObject.cs:Zeile 37.
   bei GameActivity.Controls.PluginChartTime.SetDefaultDataContext() in D:\GitHub\Lacro59\playnite-gameactivity-plugin\source\Controls\PluginChartTime.xaml.cs:Zeile 157.
   bei CommonPluginsShared.Controls.PluginUserControlExtend.GameContextChanged(Game oldContext, Game newContext) in D:\GitHub\Lacro59\playnite-gameactivity-plugin\source\playnite-plugincommon\CommonPluginsShared\Controls\PluginUserControlExtend.cs:Zeile 29.
   bei CommonPluginsShared.Controls.PluginUserControlExtendBase.PluginSettings_PropertyChanged(Object sender, PropertyChangedEventArgs e) in D:\GitHub\Lacro59\playnite-gameactivity-plugin\source\playnite-plugincommon\CommonPluginsShared\Controls\PluginUserControlExtendBase.cs:Zeile 102.
   bei GameActivity.Controls.PluginChartTime.<.ctor>b__28_2() in D:\GitHub\Lacro59\playnite-gameactivity-plugin\source\Controls\PluginChartTime.xaml.cs:Zeile 125.
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
   bei System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   bei MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Windows.Threading.DispatcherOperation.Invoke()
   bei System.Windows.Threading.Dispatcher.ProcessQueue()
   bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   bei MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   bei System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   bei System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   bei System.Windows.Application.RunDispatcher(Object ignore)
   bei System.Windows.Application.RunInternal(Window window)
   bei System.Windows.Application.Run(Window window)
   bei Playnite.DesktopApp.ProgramEntry.Main(String[] args) in C:\projects\playnite\source\Playnite.DesktopApp\ProgramEntry.cs:Zeile 61.
28-11 21:04:26.198|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ExtensionCrashHandlerWindowFactory
28-11 21:04:26.234|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory
`

**Comment by Lacro59** [comment]
Have you tried disabling the StartPage plugin and running Playnite with GameActivity?
Then activate StartPage and it should work.

**Comment by Andei** [comment]
Just tried. Crashed like the old problem

**Comment by Lacro59** [comment]
It crashes the first time you run GameActivity when the update dialog is displayed.

**Comment by Andei** [comment]
It crashes everytime with GA and SP enabled and SP launches its page on startup. Manual switching to SP doesn’t crash - just like the old problem a week ago

**Comment by Andei** [comment]
Still crashing with 2.41

**Comment by felixkmh** [comment]
Apparently initializing these fields to "true" fixes it:
https://github.com/Lacro59/playnite-gameactivity-plugin/blob/62e212bc72c294fff3defff56fb9a5c1212f0527/source/Controls/PluginChartLog.xaml.cs#L501
https://github.com/Lacro59/playnite-gameactivity-plugin/blob/62e212bc72c294fff3defff56fb9a5c1212f0527/source/Controls/PluginChartTime.xaml.cs#L436
