### ISSUE TITLE
Time not tracked when games launched in fullscreen mode

### ISSUE THREAD

**Issue by mainmango** [Lacro59/playnite-gameactivity-plugin#78]
Activity doesn't seem to get logged if I launch a game in fullscreen mode within Playnite.

Any suggestions?

**Comment by Lacro59** [comment]
Can you post your extension.log?

**Comment by mainmango** [comment]
Copied and pasted the recent portion. Should include the log when I launch it via fullscreen mode vs. desktop mode.

Thanks.

29-11 17:01:42.274|DEBUG|PlayState#PlayState:Suspend elapsed seconds for game Red Dead Redemption 2 was 92
29-11 17:01:42.274|DEBUG|PlayState#PlayState:Old playtime 123906, new playtime 123814
29-11 17:01:42.274|DEBUG|PlayState#PlayState:Stopwatch for game Red Dead Redemption 2 with id 5222cd46-907a-4bc2-9d72-e66137822641 was removed on game stopped
29-11 17:01:50.126|DEBUG|PlayState#PlayState:Hotkey registered with custom hotkey Alt, Shift + A.
29-11 17:01:51.934|INFO |GameActivity#PluginDatabaseObject`3:LoadDatabase with 46 items - 00:02.20
29-11 17:01:52.796|DEBUG|PlayState#PlayState:Changed game to Red Dead Redemption 2 game processes
29-11 17:01:57.910|DEBUG|PlayState#PlayState:Found 2 game processes
29-11 17:01:57.910|DEBUG|PlayState#PlayState:Stopwatch for game Red Dead Redemption 2 with id 5222cd46-907a-4bc2-9d72-e66137822641 was created
29-11 17:02:14.861|DEBUG|LudusaviPlaynite#LudusaviPlaynite:Running Ludusavi: backup --merge --try-update --path "E:\Games\Playnite\Save Backup" "Red Dead Redemption 2" --api
29-11 17:02:15.682|INFO |HowLongToBeat#HowLongToBeatClient:GetSubmitData(Red Dead Redemption 2)
29-11 17:02:15.966|DEBUG|LudusaviPlaynite#LudusaviPlaynite:Ludusavi exited with 0 and valid JSON content
29-11 17:02:16.661|INFO |HowLongToBeat#HowLongToBeatClient:GetSubmitData(Red Dead Redemption 2)
29-11 17:02:23.055|DEBUG|PlayState#PlayState:Hotkey registered with custom hotkey Alt, Shift + A.
29-11 17:02:25.104|INFO |GameActivity#PluginDatabaseObject`3:LoadDatabase with 46 items - 00:02.43
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.328|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.337|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.337|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.337|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.337|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.337|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.337|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.337|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.337|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.337|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.337|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.337|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.337|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.337|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.337|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.337|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.337|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.337|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.337|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.337|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.337|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.337|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.337|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.337|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.337|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:27.351|WARN |GameActivity#PlayniteTools:No PlatformsIds for 00000000-0000-0000-0000-000000000000
29-11 17:02:33.650|DEBUG|PlayState#PlayState:Changed game to Red Dead Redemption 2 game processes
29-11 17:02:38.746|DEBUG|PlayState#PlayState:Found 2 game processes
29-11 17:02:38.746|DEBUG|PlayState#PlayState:Stopwatch for game Red Dead Redemption 2 with id 5222cd46-907a-4bc2-9d72-e66137822641 was created
29-11 17:02:55.433|DEBUG|LudusaviPlaynite#LudusaviPlaynite:Running Ludusavi: backup --merge --try-update --path "E:\Games\Playnite\Save Backup" "Red Dead Redemption 2" --api
29-11 17:02:56.284|INFO |HowLongToBeat#HowLongToBeatClient:GetSubmitData(Red Dead Redemption 2)
29-11 17:02:56.427|DEBUG|LudusaviPlaynite#LudusaviPlaynite:Ludusavi exited with 0 and valid JSON content
29-11 17:02:57.206|INFO |HowLongToBeat#HowLongToBeatClient:GetSubmitData(Red Dead Redemption 2)

**Comment by Lacro59** [comment]
Can you try with the last release?
