### ISSUE TITLE
Crash on game exit

### ISSUE THREAD

**Issue by zany130** [Lacro59/playnite-gameactivity-plugin#90]
![Screenshot (2)](https://user-images.githubusercontent.com/25832539/148670349-1f2d1926-c330-4334-97c9-aa00f37c5750.png)
looking at [playnite.log](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7834512/playnite.log) something that's strange apart from the crash is that it recorded the playtime as 0 seconds when I was playing for hours

**Comment by zany130** [comment]
still happening on latest version
[extensions.log](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7865378/extensions.log)
[playnite.log](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7865379/playnite.log)
n

**Comment by Lacro59** [comment]
The fix is not still released.
Be waiting.

**Comment by Hernald** [comment]
I'm still getting the issue after the latest release.
[playnite.00007.log](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7962963/playnite.00007.log)
[playnite.00008.log](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7962964/playnite.00008.log)
[playnite.log](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7962965/playnite.log)
[extensions.00000.log](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7962966/extensions.00000.log)
[extensions.00001.log](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7962967/extensions.00001.log)
[extensions.log](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7962968/extensions.log)
