### ISSUE TITLE
Game Activity stopped tracking play time on desktop

### ISSUE THREAD

**Issue by apachpoland** [Lacro59/playnite-gameactivity-plugin#99]
Hi Larco59,

Two days ago I noticed that my Game Activity plugin doesn't collect playtime activity on desktyop version. It looks like Playnite knows that game was launched, but chart doesn't reflect that. Below you can see screenshots which I uploaded to Discord.

1 https://cdn.discordapp.com/attachments/808419165311467630/934929886471155742/unknown.png
2 https://cdn.discordapp.com/attachments/808419165311467630/934930013734707300/unknown.png
3 https://cdn.discordapp.com/attachments/808419165311467630/934935082601447484/unknown.png

Also below you can find log files as well.
[extensions.log](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7923707/extensions.log)
[playnite.log](https://github.com/Lacro59/playnite-gameactivity-plugin/files/7923708/playnite.log)

**Comment by Lacro59** [comment]
Can you post one plugin data file with the issue?
You can find this in ".\ExtensionData\afbb1a0d-04a1-4d0c-9afa-c6e42ca855b4\GameActivity\".

**Comment by apachpoland** [comment]
There are 90 files in this folder. Most of them are 1KB, few 13-16 KB. This is a first one in the row.

**Comment by apachpoland** [comment]
Im not able to upload *.json file here. Please find a source of this file.

{"Items":[{"SourceID":"1be1ee8c-f83c-4690-9525-60f57a9c2d79","PlatformID":"00000000-0000-0000-0000-000000000000","PlatformIDs":["cb49bb61-f1be-440b-9a96-5fb2af545e12"],"IdConfiguration":0,"DateSession":"2022-01-07T22:02:22.3329523Z","ElapsedSeconds":12160,"GameActionName":"Default"},{"SourceID":"1be1ee8c-f83c-4690-9525-60f57a9c2d79","PlatformID":"00000000-0000-0000-0000-000000000000","PlatformIDs":["cb49bb61-f1be-440b-9a96-5fb2af545e12"],"IdConfiguration":0,"DateSession":"2022-01-14T19:00:08.7548906Z","ElapsedSeconds":1890,"GameActionName":"Default"},{"SourceID":"1be1ee8c-f83c-4690-9525-60f57a9c2d79","PlatformID":"00000000-0000-0000-0000-000000000000","PlatformIDs":["cb49bb61-f1be-440b-9a96-5fb2af545e12"],"IdConfiguration":0,"DateSession":"2022-01-14T19:32:24.6116925Z","ElapsedSeconds":8390,"GameActionName":"Default"},{"SourceID":"1be1ee8c-f83c-4690-9525-60f57a9c2d79","PlatformID":"00000000-0000-0000-0000-000000000000","PlatformIDs":["cb49bb61-f1be-440b-9a96-5fb2af545e12"],"IdConfiguration":0,"DateSession":"2022-01-19T22:10:05.5176762Z","ElapsedSeconds":77,"GameActionName":"Default action"},{"SourceID":"1be1ee8c-f83c-4690-9525-60f57a9c2d79","PlatformID":"00000000-0000-0000-0000-000000000000","PlatformIDs":["cb49bb61-f1be-440b-9a96-5fb2af545e12"],"IdConfiguration":0,"DateSession":"2022-01-21T22:31:39.115037Z","ElapsedSeconds":0,"GameActionName":"Default action"},{"SourceID":"1be1ee8c-f83c-4690-9525-60f57a9c2d79","PlatformID":"00000000-0000-0000-0000-000000000000","PlatformIDs":["cb49bb61-f1be-440b-9a96-5fb2af545e12"],"IdConfiguration":0,"DateSession":"2022-01-21T22:33:08.1980059Z","ElapsedSeconds":0,"GameActionName":"Default action"},{"SourceID":"1be1ee8c-f83c-4690-9525-60f57a9c2d79","PlatformID":"00000000-0000-0000-0000-000000000000","PlatformIDs":["cb49bb61-f1be-440b-9a96-5fb2af545e12"],"IdConfiguration":0,"DateSession":"2022-01-22T20:42:24.3547499Z","ElapsedSeconds":0,"GameActionName":"Default action"},{"SourceID":"1be1ee8c-f83c-4690-9525-60f57a9c2d79","PlatformID":"00000000-0000-0000-0000-000000000000","PlatformIDs":["cb49bb61-f1be-440b-9a96-5fb2af545e12"],"IdConfiguration":0,"DateSession":"2022-01-23T19:14:08.2934838Z","ElapsedSeconds":0,"GameActionName":"Default action"}],"ItemsDetails":{"Items":{"2022-01-07T22:02:22.3329523Z":[{"datelog":"2022-01-07T22:07:39.3079789Z","fps":57,"cpu":72,"gpu":79,"ram":65,"cpuT":59,"gpuT":51},{"datelog":"2022-01-07T22:12:38.9534055Z","fps":59,"cpu":74,"gpu":80,"ram":63,"cpuT":62,"gpuT":54},{"datelog":"2022-01-07T22:17:38.7309008Z","fps":60,"cpu":67,"gpu":75,"ram":63,"cpuT":58,"gpuT":56},{"datelog":"2022-01-07T22:22:38.794864Z","fps":60,"cpu":58,"gpu":82,"ram":66,"cpuT":58,"gpuT":56},{"datelog":"2022-01-07T22:27:39.0001931Z","fps":59,"cpu":80,"gpu":78,"ram":66,"cpuT":58,"gpuT":53},{"datelog":"2022-01-07T22:32:38.7822477Z","fps":59,"cpu":67,"gpu":80,"ram":64,"cpuT":57,"gpuT":56},{"datelog":"2022-01-07T22:37:38.7536919Z","fps":60,"cpu":73,"gpu":80,"ram":63,"cpuT":57,"gpuT":51},{"datelog":"2022-01-07T22:42:38.9297137Z","fps":59,"cpu":62,"gpu":81,"ram":62,"cpuT":59,"gpuT":57},{"datelog":"2022-01-07T22:47:39.0944046Z","fps":58,"cpu":72,"gpu":78,"ram":62,"cpuT":64,"gpuT":57},{"datelog":"2022-01-07T22:52:38.8236537Z","fps":59,"cpu":66,"gpu":78,"ram":63,"cpuT":58,"gpuT":53},{"datelog":"2022-01-07T22:57:38.8417235Z","fps":60,"cpu":67,"gpu":78,"ram":63,"cpuT":59,"gpuT":54},{"datelog":"2022-01-07T23:02:38.8523413Z","fps":60,"cpu":68,"gpu":78,"ram":57,"cpuT":59,"gpuT":53},{"datelog":"2022-01-07T23:07:38.7902926Z","fps":59,"cpu":55,"gpu":80,"ram":57,"cpuT":60,"gpuT":57},{"datelog":"2022-01-07T23:12:38.7931254Z","fps":60,"cpu":67,"gpu":79,"ram":57,"cpuT":55,"gpuT":56},{"datelog":"2022-01-07T23:17:38.8083956Z","fps":59,"cpu":56,"gpu":78,"ram":57,"cpuT":58,"gpuT":53},{"datelog":"2022-01-07T23:22:38.8947036Z","fps":60,"cpu":61,"gpu":82,"ram":57,"cpuT":58,"gpuT":53},{"datelog":"2022-01-07T23:27:39.6213985Z","fps":530,"cpu":80,"gpu":22,"ram":60,"cpuT":58,"gpuT":50},{"datelog":"2022-01-07T23:32:38.8881762Z","fps":59,"cpu":66,"gpu":79,"ram":62,"cpuT":61,"gpuT":51},{"datelog":"2022-01-07T23:37:39.1406017Z","fps":59,"cpu":68,"gpu":77,"ram":62,"cpuT":63,"gpuT":56},{"datelog":"2022-01-07T23:42:38.8398219Z","fps":60,"cpu":48,"gpu":30,"ram":57,"cpuT":54,"gpuT":48},{"datelog":"2022-01-07T23:47:39.0490941Z","fps":59,"cpu":68,"gpu":81,"ram":62,"cpuT":61,"gpuT":56},{"datelog":"2022-01-07T23:52:38.9750427Z","fps":57,"cpu":65,"gpu":80,"ram":61,"cpuT":59,"gpuT":52},{"datelog":"2022-01-07T23:57:39.1992389Z","fps":58,"cpu":72,"gpu":77,"ram":62,"cpuT":59,"gpuT":53},{"datelog":"2022-01-08T00:02:39.1377088Z","fps":53,"cpu":70,"gpu":84,"ram":59,"cpuT":59,"gpuT":56},{"datelog":"2022-01-08T00:07:39.0056603Z","fps":60,"cpu":68,"gpu":78,"ram":58,"cpuT":58,"gpuT":52},{"datelog":"2022-01-08T00:12:38.8187031Z","fps":59,"cpu":74,"gpu":41,"ram":57,"cpuT":54,"gpuT":49},{"datelog":"2022-01-08T00:17:39.0724192Z","fps":58,"cpu":74,"gpu":77,"ram":62,"cpuT":58,"gpuT":51},{"datelog":"2022-01-08T00:22:38.9619202Z","fps":59,"cpu":67,"gpu":87,"ram":62,"cpuT":59,"gpuT":54},{"datelog":"2022-01-08T00:27:39.716822Z","fps":57,"cpu":80,"gpu":60,"ram":64,"cpuT":59,"gpuT":57},{"datelog":"2022-01-08T00:32:39.1120426Z","fps":60,"cpu":77,"gpu":80,"ram":65,"cpuT":59,"gpuT":55},{"datelog":"2022-01-08T00:37:39.3018093Z","fps":57,"cpu":62,"gpu":79,"ram":66,"cpuT":59,"gpuT":55},{"datelog":"2022-01-08T00:42:39.1177555Z","fps":59,"cpu":67,"gpu":78,"ram":64,"cpuT":62,"gpuT":53},{"datelog":"2022-01-08T00:47:39.118551Z","fps":60,"cpu":80,"gpu":78,"ram":64,"cpuT":63,"gpuT":54},{"datelog":"2022-01-08T00:52:39.0721956Z","fps":59,"cpu":74,"gpu":79,"ram":63,"cpuT":59,"gpuT":58},{"datelog":"2022-01-08T00:57:38.9253113Z","fps":59,"cpu":46,"gpu":57,"ram":56,"cpuT":58,"gpuT":54},{"datelog":"2022-01-08T01:02:38.9928529Z","fps":59,"cpu":66,"gpu":78,"ram":63,"cpuT":61,"gpuT":53},{"datelog":"2022-01-08T01:07:38.9959813Z","fps":59,"cpu":70,"gpu":77,"ram":63,"cpuT":61,"gpuT":57},{"datelog":"2022-01-08T01:12:39.0840101Z","fps":59,"cpu":60,"gpu":75,"ram":58,"cpuT":59,"gpuT":57},{"datelog":"2022-01-08T01:17:39.1145799Z","fps":59,"cpu":65,"gpu":76,"ram":58,"cpuT":60,"gpuT":51},{"datelog":"2022-01-08T01:22:39.0293449Z","fps":59,"cpu":73,"gpu":74,"ram":58,"cpuT":59,"gpuT":57}],"2022-01-19T22:10:05.5176762Z":[{"datelog":"2022-01-19T22:15:21.998083Z","fps":37,"cpu":33,"gpu":16,"ram":61,"cpuT":48,"gpuT":50},{"datelog":"2022-01-19T22:20:21.8882512Z","fps":40,"cpu":45,"gpu":99,"ram":61,"cpuT":54,"gpuT":62},{"datelog":"2022-01-19T22:25:21.7674242Z","fps":38,"cpu":41,"gpu":81,"ram":61,"cpuT":54,"gpuT":61}],"2022-01-14T19:32:24.6116925Z":[{"datelog":"2022-01-14T19:37:41.1865399Z","fps":59,"cpu":52,"gpu":83,"ram":66,"cpuT":54,"gpuT":57},{"datelog":"2022-01-14T19:42:41.1060456Z","fps":60,"cpu":54,"gpu":78,"ram":66,"cpuT":55,"gpuT":52},{"datelog":"2022-01-14T19:47:41.0842796Z","fps":60,"cpu":56,"gpu":79,"ram":61,"cpuT":55,"gpuT":54},{"datelog":"2022-01-14T19:52:41.1547587Z","fps":60,"cpu":49,"gpu":75,"ram":61,"cpuT":57,"gpuT":55},{"datelog":"2022-01-14T19:57:41.1189955Z","fps":59,"cpu":56,"gpu":78,"ram":61,"cpuT":56,"gpuT":53},{"datelog":"2022-01-14T20:02:41.133844Z","fps":60,"cpu":51,"gpu":77,"ram":65,"cpuT":54,"gpuT":52},{"datelog":"2022-01-14T20:07:41.1404545Z","fps":60,"cpu":47,"gpu":78,"ram":62,"cpuT":56,"gpuT":54},{"datelog":"2022-01-14T20:12:41.1095286Z","fps":59,"cpu":38,"gpu":64,"ram":54,"cpuT":49,"gpuT":52},{"datelog":"2022-01-14T20:17:41.1589423Z","fps":60,"cpu":62,"gpu":78,"ram":62,"cpuT":54,"gpuT":56},{"datelog":"2022-01-14T20:22:41.1311097Z","fps":59,"cpu":48,"gpu":82,"ram":62,"cpuT":55,"gpuT":56},{"datelog":"2022-01-14T20:27:41.1735813Z","fps":60,"cpu":58,"gpu":75,"ram":64,"cpuT":55,"gpuT":55},{"datelog":"2022-01-14T20:32:41.2089438Z","fps":60,"cpu":57,"gpu":78,"ram":65,"cpuT":57,"gpuT":58},{"datelog":"2022-01-14T20:37:41.2523235Z","fps":59,"cpu":54,"gpu":77,"ram":63,"cpuT":56,"gpuT":53},{"datelog":"2022-01-14T20:42:41.1812719Z","fps":59,"cpu":51,"gpu":77,"ram":60,"cpuT":56,"gpuT":54},{"datelog":"2022-01-14T20:47:41.2649587Z","fps":59,"cpu":49,"gpu":74,"ram":60,"cpuT":57,"gpuT":53},{"datelog":"2022-01-21T22:38:24.7379434Z","fps":42,"cpu":43,"gpu":70,"ram":66,"cpuT":48,"gpuT":58},{"datelog":"2022-01-21T22:43:24.5613601Z","fps":36,"cpu":44,"gpu":99,"ram":65,"cpuT":55,"gpuT":61},{"datelog":"2022-01-21T22:48:24.5771576Z","fps":33,"cpu":49,"gpu":83,"ram":65,"cpuT":56,"gpuT":61},{"datelog":"2022-01-21T22:53:24.6675389Z","fps":36,"cpu":46,"gpu":99,"ram":65,"cpuT":59,"gpuT":62},{"datelog":"2022-01-21T22:58:24.7160972Z","fps":35,"cpu":55,"gpu":98,"ram":65,"cpuT":60,"gpuT":61},{"datelog":"2022-01-22T20:47:41.4347625Z","fps":59,"cpu":54,"gpu":27,"ram":64,"cpuT":48,"gpuT":41},{"datelog":"2022-01-22T20:52:40.8896425Z","fps":32,"cpu":61,"gpu":98,"ram":74,"cpuT":53,"gpuT":57},{"datelog":"2022-01-22T20:57:40.8638213Z","fps":31,"cpu":60,"gpu":95,"ram":74,"cpuT":57,"gpuT":59},{"datelog":"2022-01-22T21:02:40.8673745Z","fps":32,"cpu":57,"gpu":96,"ram":73,"cpuT":62,"gpuT":60},{"datelog":"2022-01-22T21:07:40.7689259Z","fps":39,"cpu":57,"gpu":99,"ram":73,"cpuT":57,"gpuT":60},{"datelog":"2022-01-22T21:12:40.8588072Z","fps":32,"cpu":49,"gpu":93,"ram":66,"cpuT":57,"gpuT":61},{"datelog":"2022-01-22T21:17:40.8532344Z","fps":33,"cpu":44,"gpu":99,"ram":65,"cpuT":55,"gpuT":61},{"datelog":"2022-01-22T21:22:40.9308433Z","fps":36,"cpu":53,"gpu":98,"ram":62,"cpuT":57,"gpuT":61},{"datelog":"2022-01-22T21:27:40.7259655Z","fps":37,"cpu":53,"gpu":99,"ram":58,"cpuT":60,"gpuT":62},{"datelog":"2022-01-23T19:19:25.8068574Z","fps":0,"cpu":52,"gpu":99,"ram":64,"cpuT":0,"gpuT":57},{"datelog":"2022-01-23T19:24:24.6570478Z","fps":0,"cpu":46,"gpu":87,"ram":63,"cpuT":0,"gpuT":59},{"datelog":"2022-01-23T19:29:24.5758477Z","fps":0,"cpu":54,"gpu":86,"ram":63,"cpuT":0,"gpuT":59},{"datelog":"2022-01-23T19:34:24.6665475Z","fps":0,"cpu":55,"gpu":88,"ram":63,"cpuT":0,"gpuT":59},{"datelog":"2022-01-23T19:39:24.6152413Z","fps":0,"cpu":47,"gpu":70,"ram":64,"cpuT":0,"gpuT":59},{"datelog":"2022-01-23T19:44:24.5870038Z","fps":0,"cpu":58,"gpu":83,"ram":65,"cpuT":0,"gpuT":58},{"datelog":"2022-01-23T19:49:24.6903315Z","fps":0,"cpu":52,"gpu":95,"ram":62,"cpuT":0,"gpuT":60},{"datelog":"2022-01-23T19:54:24.5710147Z","fps":0,"cpu":46,"gpu":85,"ram":57,"cpuT":0,"gpuT":56},{"datelog":"2022-01-23T19:59:24.5685241Z","fps":0,"cpu":48,"gpu":88,"ram":57,"cpuT":0,"gpuT":61},{"datelog":"2022-01-23T20:04:24.7348611Z","fps":0,"cpu":47,"gpu":89,"ram":60,"cpuT":0,"gpuT":61},{"datelog":"2022-01-23T20:09:24.6710005Z","fps":0,"cpu":31,"gpu":31,"ram":59,"cpuT":0,"gpuT":53},{"datelog":"2022-01-23T20:14:24.7364621Z","fps":0,"cpu":41,"gpu":78,"ram":59,"cpuT":0,"gpuT":60},{"datelog":"2022-01-23T20:19:24.7390309Z","fps":0,"cpu":61,"gpu":97,"ram":61,"cpuT":0,"gpuT":62},{"datelog":"2022-01-23T20:24:24.7372118Z","fps":0,"cpu":45,"gpu":80,"ram":59,"cpuT":0,"gpuT":59},{"datelog":"2022-01-23T20:29:24.779493Z","fps":0,"cpu":60,"gpu":79,"ram":60,"cpuT":0,"gpuT":60},{"datelog":"2022-01-23T20:34:24.7902788Z","fps":0,"cpu":54,"gpu":99,"ram":59,"cpuT":0,"gpuT":62},{"datelog":"2022-01-23T20:39:24.7696039Z","fps":0,"cpu":44,"gpu":87,"ram":58,"cpuT":0,"gpuT":61},{"datelog":"2022-01-23T20:44:24.7736317Z","fps":0,"cpu":57,"gpu":94,"ram":58,"cpuT":0,"gpuT":61},{"datelog":"2022-01-23T20:49:24.8283036Z","fps":0,"cpu":75,"gpu":93,"ram":58,"cpuT":0,"gpuT":61},{"datelog":"2022-01-23T20:54:24.8462139Z","fps":0,"cpu":58,"gpu":87,"ram":57,"cpuT":0,"gpuT":61},{"datelog":"2022-01-23T20:59:24.7328639Z","fps":0,"cpu":51,"gpu":92,"ram":57,"cpuT":0,"gpuT":61},{"datelog":"2022-01-23T21:04:24.80032Z","fps":0,"cpu":53,"gpu":81,"ram":55,"cpuT":0,"gpuT":60},{"datelog":"2022-01-23T21:09:24.7002153Z","fps":0,"cpu":66,"gpu":30,"ram":61,"cpuT":0,"gpuT":53},{"datelog":"2022-01-23T21:14:24.884465Z","fps":0,"cpu":44,"gpu":84,"ram":61,"cpuT":0,"gpuT":59},{"datelog":"2022-01-23T21:19:24.8781845Z","fps":0,"cpu":58,"gpu":87,"ram":62,"cpuT":0,"gpuT":59},{"datelog":"2022-01-23T21:24:24.8452267Z","fps":0,"cpu":50,"gpu":96,"ram":62,"cpuT":0,"gpuT":60},{"datelog":"2022-01-23T21:29:24.9298861Z","fps":0,"cpu":61,"gpu":96,"ram":62,"cpuT":0,"gpuT":61}],"2022-01-23T19:14:08.2934838Z":[],"2022-01-22T20:42:24.3547499Z":[],"2022-01-21T22:33:08.1980059Z":[],"2022-01-14T19:00:08.7548906Z":[{"datelog":"2022-01-14T19:05:27.1391605Z","fps":59,"cpu":30,"gpu":7,"ram":65,"cpuT":54,"gpuT":50},{"datelog":"2022-01-14T19:10:25.2201034Z","fps":59,"cpu":53,"gpu":75,"ram":67,"cpuT":58,"gpuT":55},{"datelog":"2022-01-14T19:15:25.1914542Z","fps":60,"cpu":62,"gpu":78,"ram":67,"cpuT":55,"gpuT":57},{"datelog":"2022-01-14T19:20:25.1789852Z","fps":60,"cpu":56,"gpu":84,"ram":62,"cpuT":55,"gpuT":58},{"datelog":"2022-01-14T19:25:25.2123726Z","fps":59,"cpu":53,"gpu":79,"ram":62,"cpuT":57,"gpuT":52},{"datelog":"2022-01-14T19:30:25.2001453Z","fps":60,"cpu":54,"gpu":77,"ram":60,"cpuT":54,"gpuT":56}],"2022-01-21T22:31:39.115037Z":[]}},"Id":"2ea6b7f0-6b14-49f0-8075-7a4e3ecf248a","Name":"Sniper Ghost Warrior Contracts"}

**Comment by apachpoland** [comment]
{"Items":[{"SourceID":"4d92f712-d902-4841-9a2c-39ac39e63c6e","PlatformID":"00000000-0000-0000-0000-000000000000","PlatformIDs":["cb49bb61-f1be-440b-9a96-5fb2af545e12"],"IdConfiguration":0,"DateSession":"2022-01-22T21:32:57.8426676Z","ElapsedSeconds":0,"GameActionName":"Default action"},{"SourceID":"4d92f712-d902-4841-9a2c-39ac39e63c6e","PlatformID":"00000000-0000-0000-0000-000000000000","PlatformIDs":["cb49bb61-f1be-440b-9a96-5fb2af545e12"],"IdConfiguration":0,"DateSession":"2022-01-22T21:50:47.9322678Z","ElapsedSeconds":0,"GameActionName":"Default action"},{"SourceID":"4d92f712-d902-4841-9a2c-39ac39e63c6e","PlatformID":"00000000-0000-0000-0000-000000000000","PlatformIDs":["cb49bb61-f1be-440b-9a96-5fb2af545e12"],"IdConfiguration":0,"DateSession":"2022-01-23T22:09:55.0122254Z","ElapsedSeconds":0,"GameActionName":"Default action"}],"ItemsDetails":{"Items":{"2022-01-23T22:09:55.0122254Z":[],"2022-01-22T21:32:57.8426676Z":[],"2022-01-22T21:50:47.9322678Z":[]}},"Id":"eb56b006-d263-4645-b345-8ea8257b9f0d","Name":"StarCraft II"}

**Comment by apachpoland** [comment]
I was able to provide files for a games from screenshots above.
